---
author:
  email: 
  name: An Author
  twitter: 
  url: 
baseurl: "/egypt-handbook-for-travellers"
collections:
  annotations:
    output: true
    permalink: "/annotations/:path/"
  volume_pages:
    output: true
    permalink: "/pages/:path/"
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    layout: volume_page
    short_label: p.
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://readux.ecds.emory.edu/books/emory:bs1xr/pages/emory:gkqhw/single-page/
image_size:
  page:
    width: 729
    height: 1000
  thumbnail:
    width: 218
    height: 300
  small-thumbnail:
    width: 72
    height: 100
permalink: pretty
publication_info:
  title: Egypt  handbook for travellers , an annotated digital edition
  date: '2018'
  author: Karl Baedeker (Firm)
  editors:
  - Joanna Mundy
  tei_xml: tei.xml
show_annotation_author: true
source_info:
  title: 'Egypt  handbook for travellers '
  author: Karl Baedeker (Firm)
  date: '1902'
  url: https://readux.ecds.emory.edu/books/emory:bs1xr/
  pdf_url: https://readux.ecds.emory.edu/books/emory:bs1xr/pdf/#page=2
  via_readux: true
tagline: ", an annotated digital edition"
title: 'Egypt  handbook for travellers '
url: https://jcmundy.github.io
version: 0.7
